module.exports = function (grunt) {

    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),

        uglify: {
            options: {
                banner: '/*! <%= pkg.name %> <%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
            },
            build: {
                src: '_ui/js/*.js',
                dest: '_ui/compiled/app.min.js'
            }
        },

        sass: {
            dev: {
                options: {
                    style: 'expanded',
                    debugInfo: true,
                    lineNumbers: true
                },
                files: {
                    '_ui/css/main.css': '_ui/css/main.scss'
                }
            },
            dist: {
                options: {
                    debugInfo: false
                },
                files: {
                    '_ui/compiled/main.min.css': '_ui/css/main.scss'
                }
            }
        },

        cssmin: {
            dist: {
                options: {
                    banner: '/*! <%= pkg.name %> <%= pkg.version %> <%= grunt.template.today("yyyy-mm-dd HH:MM") %> */\n'
                },
                files: {
                    '_ui/compiled/main.min.css': ['_ui/compiled/main.min.css']
                }
            }
        },

        watch: {
            // gsass: {
            //     files: ['_ui/css/sass/*.scss'],
            //     tasks: ['sass:dev', 'shell:growlSass']
            // },
            sass: {
                files: ['_ui/css/sass/*.scss'],
                tasks: ['sass', 'cssmin']
            }
        }//,

        // shell: {
        //     growlSass: {
        //         command: 'growlnotify -m "Sass Compiled" "nkatarow" --image _ui/img/favicon@2x.png'
        //     },
        //     growlBuilt: {
        //         command: 'growlnotify -m "Build Complete" "nkatarow" --image _ui/img/favicon@2x.png'
        //     }
        // }
    });

    // NPM tasks
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-sass');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-shell');

    // Grunt tasks
    grunt.registerTask('default', ['uglify', 'sass', 'cssmin']);
    //grunt.registerTask('default', ['scriptblock', 'uglify', 'sass', 'cssmin', 'shell:growlBuilt']);

    // Requires Growl + GrowlNotify - http://growl.cachefly.net/GrowlNotify-2.0.zip
    //grunt.registerTask('gwatch', ['watch:gsass']);

    // grunt.registerTask('scriptblock', 'Emit a HTML partial containing all script includes.', function () {
    //     var html = '<?php // AUTO-GENERATED BY GRUNT. To change this block edit Gruntfile.js, not this file! ?>' + "\n\n",
    //         files;

    //     scriptList.forEach(function (path) {
    //         files = grunt.file.expand(path);

    //         files.forEach(function (file) {
    //             html += '<script src="<?php echo $app->dir(\'base\'); ?>' + file + '"></script>' + "\n";
    //         });
    //     });

    //     grunt.file.write('sites/all/themes/tradecraft/templates/html/scripts.php', html);
    // });
};
